spring:
  session:
    store-type: redis
  application:
    name: authentication
  redis:
    host: redis
    port: 6379
  datasource:
    url: "jdbc:postgresql://authentication-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      # We should rather use Flyway. But for simplicity, here rely
      # on Hibernate to handle the schema (which is usually not a good idea).
      ddl-auto: "update"
    properties:
      hibernate:
        jdbc:
          lob:  # Disables error-like log in console:
            non_contextual_creation: true


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
