spring:
  session:
    store-type: redis
  application:
    name: authentication
  redis:
    host: redis
    port: 6379
  datasource:
    url: "jdbc:postgresql://authentication-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: create-drop
    show-sql: true


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
