version: '3.3'

services:
  #### DATABASE ####
  post-db:
    image: "postgres:10"

  authentication-db:
    image: "postgres:10"

  user-db:
    image: "postgres:10"

    #### RABBITMQ ####
    #rabbitmq:
    #image: "rabbitmq:3"

  #### REDIS ####
  redis:
    image: "redis:latest"

  #### GATEWAY ####
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - eureka
      - redis

  #### EUREKA ####
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile

  #### AUTHENTICATION ####
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    depends_on:
      - redis
      - gateway
      - authentication-db
  ### USER ####
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - redis
      - gateway
      - user-db

  ### FRONTEND ####
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - gateway

  ### POST ####
  post1:
    build:
      context: ./post
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - post-db
      - redis

  post2:
    build:
      context: ./post
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - post-db
      - redis
