spring:
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: movie
          uri: http://movie
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - StripPrefix=2

        - id: user
          uri: http://user
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: authentication
          uri: http://authentication
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2

        - id: frontend
          uri: http://frontend
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

