# Got inspiration from:
# https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/security/distributed-session/ds-user-service/src/main/resources/application.yml

userServiceAddress: "user:8080"

# From Andrea's repository.
spring:
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  application:
    name: post
  datasource:
    url: "jdbc:postgresql://post-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    show-sql: true
    hibernate:
      ddl-auto: validate


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

post:
  ribbon:
    eureka:
      enabled: true
