userServiceAddress: "user:8080"

# From Andrea's repository.
spring:
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  application:
    name: post
  datasource:
    url: "jdbc:postgresql://post-db:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "create-drop"
    properties:
      hibernate:
        jdbc:
          lob:  # Disables error-like log in console:
            non_contextual_creation: true

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

post:
  ribbon:
    eureka:
      enabled: true
